### ISSUE TITLE
Create Checkout Page

### ISSUE THREAD

**Issue by FeliciaKh** [Team-One-Grace-Shopper/GraceShopper#13]
Visitor: After clicking on the checkout button on the edit cart page, the user is seeing the checkout page. They are able to input their address and payment method. There is also a place order button in the order summary section. The order summary has the product name, price, selected quantity, and subtotal for each item with the items total, shipping amount, tax amount with the order total. 

Implementation: 
- create checkout component;
- for Tier 1 don't need to store/validate address and payment method; 
- need to create conformation page, which will be render after checkout.

**Comment by alesin** [comment]
@FeliciaKh @marybelousova @ChidiOk Somebody may be able to start on this now that I added a cart page... I'm still working on the add & edit features of the cart, but someone could start on a checkout page with a "submit order" feature just using the current un-editable cart.
