### ISSUE TITLE
Create functionality: add a product to our cart

### ISSUE THREAD

**Issue by marybelousova** [Team-One-Grace-Shopper/GraceShopper#46]
As a customer/visitor,  I want to be able add a product to my cart so I can collect my desired products in one place.

Implementation: 
- create a button on front-end for "add to the cart"
- back-end

**Comment by alesin** [comment]
So I refactored the seed file to work out some of the backend mechanics for this. I added documentation via comments above each section. I'd love for everyone to review... and now I just need to figure out how to generate a PR... @marybelousova @ChidiOk @FeliciaKh
